import type { AuditgenConfig } from "../config.js";
import type { Finding, Framework, Report } from "../types.js";

/**
 * Generates the two documents an auditor asks for and a consultant charges for.
 *
 * Both are marked as DRAFT and complete-in-place by a human. auditgen cannot know
 * your personnel, your commitments to customers, or your risk appetite, so it
 * pre-fills only what it observed and marks the rest as an explicit TODO rather
 * than inventing plausible prose. Inventing a System Description is worse than
 * leaving it blank, because a blank field gets answered and a plausible one gets
 * signed.
 */

function statusOf(f: Finding): string {
  switch (f.status) {
    case "satisfied":
      return "Implemented";
    case "partial":
      return "Partially implemented";
    case "manual":
      return "Not yet evidenced";
    case "not_applicable":
      return "Excluded";
    default:
      return "Gap";
  }
}

function findingsFor(report: Report, framework: Framework): Finding[] {
  return report.findings.filter((f) => f.control.framework === framework);
}

function escapePipes(value: string): string {
  return value.replace(/\|/g, "\\|");
}

const TODO = "<!-- TODO: complete before submitting to the auditor -->";

/** Controls observed to be operating, with the evidence that shows it. */
function evidenceTable(findings: Finding[]): string[] {
  const lines = ["| Control | Title | Status | Evidence |", "| --- | --- | --- | --- |"];
  for (const f of findings) {
    const passing = f.evidence.filter((e) => e.passed);
    const evidence =
      passing.length > 0
        ? passing.map((e) => escapePipes(e.title)).join("<br>")
        : escapePipes(f.evidence[0]?.title ?? "no evidence collected");
    lines.push(
      `| \`${f.control.id}\` | ${escapePipes(f.control.title)} | ${statusOf(f)} | ${evidence} |`,
    );
  }
  return lines;
}

export interface DocInput {
  report: Report;
  config: AuditgenConfig;
  /** Period the report covers, free text, e.g. "1 April 2026 to 30 June 2026". */
  period?: string;
  preparedBy?: string;
}

export function generateSystemDescription(input: DocInput): string {
  const { report, config, period } = input;
  const org = config.organizationName ?? "<organization name>";
  const system = config.systemName ?? `${report.target.owner}/${report.target.repo}`;
  const window = period ?? "<start date> to <end date>";
  const data = config.dataCategories ?? [];

  const lines: string[] = [];
  lines.push("# System Description");
  lines.push("");
  lines.push(`**${org} — ${system}**`);
  lines.push("");
  lines.push("> DRAFT generated by auditgen. Generated from repository and hosting");
  lines.push("> configuration only. Every field marked TODO requires a human decision.");
  lines.push("");

  lines.push("## 1. Organization and scope");
  lines.push("");
  lines.push(`This System Description applies to ${system} for the period ${window}.`);
  lines.push("");
  lines.push("| | |");
  lines.push("| --- | --- |");
  lines.push(`| Reporting entity | ${org} |`);
  lines.push(`| System | ${system} |`);
  lines.push(`| Repository | https://github.com/${report.target.owner}/${report.target.repo} |`);
  lines.push(`| Primary branch | ${report.target.defaultBranch ?? "main"} |`);
  lines.push(`| Period covered | ${window} |`);
  lines.push(`| Prepared by | ${input.preparedBy ?? TODO} |`);
  lines.push("");

  lines.push("## 2. Services");
  lines.push("");
  lines.push(config.systemDescription ?? TODO);
  lines.push("");
  lines.push(`TODO: confirm whether any service in the period changed materially, and list`);
  lines.push("each change with its date and approval. A change in the period that is not");
  lines.push("described here is the single most common scope dispute in an examination.");
  lines.push("");

  lines.push("## 3. Principal service commitments");
  lines.push("");
  lines.push(`TODO: state the commitments made to customers about ${system}. For a software`);
  lines.push("product this usually means uptime, security and data-protection commitments");
  lines.push("made in a customer agreement, status page or public documentation. The");
  lines.push("commitments define what the control environment has to support.");
  lines.push("");

  lines.push("## 4. Components of the system");
  lines.push("");
  lines.push("### 4.1 Infrastructure");
  lines.push("");
  lines.push(
    config.hostingEnvironment ??
      TODO,
  );
  lines.push("");
  lines.push("### 4.2 Software");
  lines.push("");
  lines.push(
    `- Source repository: https://github.com/${report.target.owner}/${report.target.repo}`,
  );
  lines.push(
    `- Continuous integration: ${report.findings.some((f) => f.control.collector === "github.ci_workflows") ? "GitHub Actions" : TODO}`,
  );
  lines.push(
    `- Dependency vulnerability monitoring: ${report.findings.some((f) => f.control.collector === "github.dependabot") ? "Dependabot" : TODO}`,
  );
  lines.push("");
  lines.push("### 4.3 People");
  lines.push("");
  lines.push(`TODO: list the roles responsible for operating ${system}, who holds each role,`);
  lines.push("and how role assignment is authorized and reviewed. Include the person who");
  lines.push("owns access provisioning and the person who performs access reviews.");
  lines.push("");
  lines.push("### 4.4 Data");
  lines.push("");
  if (data.length > 0) {
    for (const category of data) lines.push(`- ${category}`);
  } else {
    lines.push(TODO);
    lines.push("");
    lines.push(
      "TODO: enumerate the categories of information processed, where each is stored,",
    );
    lines.push(
      "and the retention period. This drives the confidentiality and privacy criteria",
    );
    lines.push("in scope and cannot be inferred from source code.");
  }
  lines.push("");
  lines.push("### 4.5 Processes");
  lines.push("");
  lines.push(
    "Change management, access provisioning, incident response and vulnerability",
  );
  lines.push(
    "remediation processes are evidenced in the control matrix of the accompanying",
  );
  lines.push("compliance report. Narrative descriptions of each process belong here.");
  lines.push("");
  lines.push(`TODO: describe each process, its owner, and the record it produces.`);
  lines.push("");

  lines.push("## 5. Subservice organizations");
  lines.push("");
  lines.push("TODO: list every third party with access to in-scope data or systems,");
  lines.push("including the cloud or hosting provider, and note whether a complementary");
  lines.push("user entity control or carve-out method has been agreed with them.");
  lines.push("");
  lines.push(
    "If a subservice organization is carved out of the examination, its controls must be",
  );
  lines.push("described here or the affected criteria will not be covered.");
  lines.push("");

  lines.push("## 6. User entity responsibilities");
  lines.push("");
  lines.push("TODO: describe the controls ${org} operates that support the commitments");
  lines.push("in section 3, and the complementary user entity controls a customer is");
  lines.push("expected to implement. Missing this section is the most common cause of a");
  lines.push("qualified report.");
  lines.push("");

  lines.push("## 7. Criteria in scope");
  lines.push("");
  const tsc =
    config.trustServicesCriteria ?? ["Security (Common Criteria, CC1–CC9)"];
  for (const criterion of tsc) lines.push(`- ${criterion}`);
  lines.push("");
  if (!report.frameworks.includes("soc2")) {
    lines.push(
      "_No SOC 2 criteria were evaluated in this run. Re-run with `--framework soc2`._",
    );
    lines.push("");
  }

  lines.push("## 8. Supporting evidence");
  lines.push("");
  lines.push(
    "The observations underpinning this description are recorded in the accompanying",
  );
  lines.push("compliance report, whose evidence chain root is:");
  lines.push("");
  lines.push("```");
  lines.push(report.evidenceRoot);
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

export function generateStatementOfApplicability(input: DocInput): string {
  const { report, config } = input;
  const org = config.organizationName ?? "<organization name>";
  const system = config.systemName ?? `${report.target.owner}/${report.target.repo}`;
  const iso = findingsFor(report, "iso27001");

  const lines: string[] = [];
  lines.push("# Statement of Applicability");
  lines.push("");
  lines.push(`**${org} — ${system}**`);
  lines.push("");
  lines.push("> DRAFT generated by auditgen against ISO/IEC 27001:2022 Annex A.");
  lines.push("> auditgen evaluates the controls observable from source control and hosting");
  lines.push("> configuration. Controls marked *Not yet evidenced* have not been assessed, not");
  lines.push("> been found deficient. Complete the full Annex A before certification.");
  lines.push("");

  lines.push("## 1. Scope of the ISMS");
  lines.push("");
  lines.push(
    config.systemDescription ?? TODO,
  );
  lines.push("");
  lines.push(`| | |`);
  lines.push("| --- | --- |");
  lines.push(`| ISMS scope | ${system} |`);
  lines.push(`| Repository | https://github.com/${report.target.owner}/${report.target.repo} |`);
  lines.push(`| Criteria | ISO/IEC 27001:2022 Annex A |`);
  lines.push(`| Controls in this statement | ${iso.length} of 93 |`);
  lines.push("");

  lines.push("## 2. Applicability and implementation");
  lines.push("");
  lines.push(
    "| Control | Title | Applicable | Status | Basis |",
  );
  lines.push("| --- | --- | --- | --- | --- |");
  for (const f of iso) {
    const basis =
      f.status === "satisfied"
        ? escapePipes(
            f.evidence.find((e) => e.passed)?.title ?? "observed in configuration",
          )
        : escapePipes(f.gaps[0] ?? "not yet assessed");
    lines.push(
      `| \`${f.control.id}\` | ${escapePipes(f.control.title)} | Yes | ${statusOf(f)} | ${basis} |`,
    );
  }
  lines.push("");

  lines.push("## 3. Excluded controls");
  lines.push("");
  lines.push(
    "TODO: record any Annex A control judged inapplicable, with a justification tied to",
  );
  lines.push(
    "the risk assessment. ISO/IEC 27001:2022 permits exclusion but requires a",
  );
  lines.push("documented justification; an unexplained exclusion is a nonconformity.");
  lines.push("");

  lines.push("## 4. Risk treatment and control mapping");
  lines.push("");
  lines.push(
    "TODO: map each applicable control to the risks it treats, using the risk register",
  );
  lines.push(
    "produced by the risk assessment. This mapping is what converts a list of controls",
  );
  lines.push("into an ISMS, and it cannot be derived from repository configuration.");
  lines.push("");

  lines.push("## 5. Controls not yet evidenced");
  lines.push("");
  const pending = iso.filter((f) => f.status !== "satisfied");
  if (pending.length === 0) {
    lines.push(
      "Every evaluated Annex A control has passing evidence. This statement still does",
    );
    lines.push("not cover the remainder of Annex A, which has not been assessed.");
  } else {
    for (const f of pending) {
      lines.push(`### ${f.control.id} — ${f.control.title}`);
      lines.push("");
      for (const gap of f.gaps) lines.push(`- ${gap}`);
      lines.push("");
    }
  }
  lines.push("");

  lines.push("## 6. Review");
  lines.push("");
  lines.push(
    "This statement should be reviewed on the same cadence as the risk assessment and,",
  );
  lines.push(
    "at minimum, whenever a control, a system boundary or a significant change alters it.",
  );
  lines.push("");
  lines.push(`Evidence chain root: \`${report.evidenceRoot}\``);
  lines.push("");

  return lines.join("\n");
}

export function generateSoaNote(controlId: string, implemented: boolean): string {
  return implemented
    ? `Control ${controlId} is implemented and its operation is evidenced by repository observation.`
    : `Control ${controlId} is applicable and its implementation is being established.`;
}